language: android
jdk:
  - oraclejdk8

script: "./gradlew build"
#android:
#  components:
#    # Uncomment the lines below if you want to
#    # use the latest revision of Android SDK Tools
#    # - oldPlatform-tools
#    # - tools
#
#    # The BuildTools version used by your project
#    - build-tools-22.0.1
#
#    # The SDK version used to compile your project
#    - android-22
#
#    # Additional components
#    - extra-google-google_play_services
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - addon-google_apis-google-19
#
#    # Specify at least one system image,
#    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-19
#    - sys-img-x86-android-17
#
#sudo: false
#
#before_script:
#  - pip install --upgrade pip
#  - pip install --user runloop
#  - pip install --user codecov
#
#
#before_install:
#  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
#  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
#
#after_success:
#  - cp app/build/jacoco/jacocoTestReport/*.xml jacoco.xml
#  - cp app/build/jacoco/jacocoTestReport/*.xml jacoco2.xml
#  - codecov
#  - bash <(curl -s https://codecov.io/bash)
#
#deploy:
#    provider: script
#    script: "./gradlew bintray"
#    on:
#      tags: true
#
#cache:
#    directories:
#    - "$HOME/.gradle/caches/"

deploy:
  provider: bintray
  user: bintrayUser
  key: bintrayApiKey






































